# -*- coding: utf-8 -*-
# 25 条不等式数据：(名称, LaTeX, 一句话注解, 六维评分[考试频率,竞赛热度,数学美感,应用广度,初等亲和,推广深度])
# 全部经过 numpy 数值验证（verify_ineq.py 25/25 PASS），评分为主观打分
PAL = ["#17B8BA", "#B89AF0", "#E868C8", "#E8944A", "#4A90D9", "#8F86E8",
       "#1FA8C8", "#40C878", "#C8C830", "#E07A4A", "#30C8C0", "#D878C8"]

INEQS = [
    ("基本不等式", r"\sqrt{ab}\le\frac{a+b}{2}\ (a,b>0)",
     "定值求最值的万能钥匙", [10, 9, 7, 9, 10, 7]),
    ("均值不等式链", r"\sqrt[n]{\prod a_i}\le\frac{1}{n}\sum a_i\le\sqrt{\frac{\sum a_i^{2}}{n}}",
     "四种平均，各居其位", [8, 8, 8, 7, 9, 8]),
    ("幂平均不等式", r"r<s\Rightarrow M_r(a)\le M_s(a)",
     "平均数也有鄙视链", [6, 7, 7, 6, 6, 8]),
    ("柯西不等式", r"\Big(\sum_{i}a_ib_i\Big)^{2}\le\sum_{i}a_i^{2}\cdot\sum_{i}b_i^{2}",
     "内积放缩，天下第一", [10, 10, 10, 10, 8, 10]),
    ("柯西积分形式", r"\Big(\int_a^b fg\,\mathrm{d}x\Big)^{2}\le\int_a^b f^{2}\,\mathrm{d}x\cdot\int_a^b g^{2}\,\mathrm{d}x",
     "连续版柯西，L2 基石", [7, 6, 8, 8, 5, 9]),
    ("嵌入不等式", r"2\sum_{i<j}a_ia_j\le(n-1)\sum_{i}a_i^{2}",
     "交叉项挤不过平方和", [5, 7, 6, 4, 7, 5]),
    ("杨氏不等式", r"ab\le\frac{a^{p}}{p}+\frac{b^{q}}{q},\ \frac{1}{p}+\frac{1}{q}=1",
     "柯西与赫尔德的发动机", [7, 6, 7, 8, 6, 9]),
    ("赫尔德不等式", r"\sum_{i}|a_ib_i|\le\Big(\sum|a_i|^{p}\Big)^{\frac{1}{p}}\Big(\sum|b_i|^{q}\Big)^{\frac{1}{q}}",
     "p q 共轭，放缩通吃", [8, 8, 8, 9, 5, 10]),
    ("赫尔德积分形式", r"\int_a^b|fg|\,\mathrm{d}x\le\Big(\int|f|^{p}\Big)^{\frac{1}{p}}\Big(\int|g|^{q}\Big)^{\frac{1}{q}}",
     "函数空间里的赫尔德", [6, 5, 7, 8, 4, 9]),
    ("闵可夫斯基不等式", r"\Big(\sum|a_i+b_i|^{p}\Big)^{\frac{1}{p}}\le\Big(\sum|a_i|^{p}\Big)^{\frac{1}{p}}+\Big(\sum|b_i|^{p}\Big)^{\frac{1}{p}}",
     "三角不等式的 p 次方版", [7, 7, 8, 8, 5, 9]),
    ("闵可夫斯基积分形式", r"\Big(\int|f+g|^{p}\Big)^{\frac{1}{p}}\le\Big(\int|f|^{p}\Big)^{\frac{1}{p}}+\Big(\int|g|^{p}\Big)^{\frac{1}{p}}",
     "Lp 空间的三角不等式", [5, 5, 7, 7, 4, 8]),
    ("三角不等式", r"\|x+y\|\le\|x\|+\|y\|",
     "两点之间，线段最短", [8, 6, 7, 9, 8, 8]),
    ("伯努利不等式", r"(1+x)^{n}\ge1+nx\ (x\ge-1)",
     "一阶泰勒就够了", [7, 7, 6, 7, 9, 6]),
    ("琴生不等式", r"f\Big(\frac{\sum x_i}{n}\Big)\le\frac{\sum f(x_i)}{n}",
     "凸函数的灵魂定理", [8, 8, 8, 9, 6, 9]),
    ("琴生积分形式", r"f\Big(\int_a^b x\,\mathrm{d}x\Big)\le\int_a^b f(x)\,\mathrm{d}x",
     "平均的函数不超过函数的平均", [6, 5, 7, 7, 5, 8]),
    ("切比雪夫不等式", r"\frac{\sum a_ib_i}{n}\ge\frac{\sum a_i}{n}\cdot\frac{\sum b_i}{n}",
     "同增同减，乘积不吃亏", [6, 8, 7, 6, 7, 7]),
    ("切比雪夫积分形式", r"\int_a^b fg\,\mathrm{d}x\ge\int_a^b f\,\mathrm{d}x\cdot\int_a^b g\,\mathrm{d}x",
     "单调函数的积分版", [5, 5, 6, 6, 5, 7]),
    ("排序不等式", r"a_i\uparrow,\ b_i\uparrow\Rightarrow\sum a_ib_i\ge\sum a_ib_{\sigma(i)}",
     "同序最大，反序最小", [6, 8, 7, 5, 8, 6]),
    ("舒尔不等式", r"\sum_{\mathrm{cyc}}a(a-b)(a-c)\ge0",
     "轮换对称的代数利器", [5, 8, 7, 4, 5, 7]),
    ("内斯比特不等式", r"\sum_{\mathrm{cyc}}\frac{a}{b+c}\ge\frac{3}{2}",
     "分式和的地板是 3/2", [6, 9, 8, 4, 8, 6]),
    ("外森比克不等式", r"a^{2}+b^{2}+c^{2}\ge4\sqrt{3}\,S",
     "平方和压得住面积", [5, 8, 8, 4, 7, 6]),
    ("欧拉不等式", r"R\ge2r",
     "外接圆至少内切圆两倍", [6, 8, 9, 5, 8, 7]),
    ("等周不等式", r"L^{2}\ge4\pi S",
     "圆是最省周长的形状", [5, 7, 10, 7, 8, 9]),
    ("哈达玛不等式", r"|\det A|\le\prod_{i}\|v_i\|",
     "行列式被行范数卡死", [6, 6, 8, 7, 5, 8]),
    ("弗罗宾尼斯不等式", r"r(AB)+r(BC)\le r(B)+r(ABC)",
     "秩的三角不等式", [4, 5, 6, 5, 3, 7]),
]
